// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-ships.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-ships.ts
var list_ships_default = defineTool({
  name: "list_ships",
  title: "Daftar kapal",
  description: "List ship unloading records (kapal) for the signed-in user, newest first. Optionally filter by month, year, or PIPP status.",
  inputSchema: {
    year: z.number().int().min(2e3).max(2100).optional().describe("Filter by year of tanggal."),
    month: z.number().int().min(1).max(12).optional().describe("Filter by month (1-12) of tanggal."),
    done_pipp: z.boolean().optional().describe("Filter by PIPP completion status."),
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, month, done_pipp, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("kapal_data").select(
      "id, nama_kapal, tanggal, jenis_pendataan, alat_tangkap, posisi_dermaga, tanda_selar_gt, tanda_selar_no, tanda_selar_huruf, done_pipp, notes"
    ).order("tanggal", { ascending: false }).limit(limit ?? 50);
    if (typeof done_pipp === "boolean") query = query.eq("done_pipp", done_pipp);
    if (year) {
      const m = month ?? 1;
      const start = month ? `${year}-${String(m).padStart(2, "0")}-01` : `${year}-01-01`;
      const endDate = month ? new Date(Date.UTC(year, m, 1)) : new Date(Date.UTC(year + 1, 0, 1));
      query = query.gte("tanggal", start).lt("tanggal", endDate.toISOString().slice(0, 10));
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { ships: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-ship-detail.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_ship_detail_default = defineTool2({
  name: "get_ship_detail",
  title: "Detail kapal & hasil bongkar",
  description: "Get one ship record with all of its catch entries (jenis, berat) plus totals per species.",
  inputSchema: {
    kapal_id: z2.string().uuid().describe("The ship record id returned by list_ships.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kapal_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: ship, error: shipError } = await supabase.from("kapal_data").select("*").eq("id", kapal_id).maybeSingle();
    if (shipError) return { content: [{ type: "text", text: shipError.message }], isError: true };
    if (!ship) return { content: [{ type: "text", text: "Kapal tidak ditemukan." }], isError: true };
    const { data: entries, error: entriesError } = await supabase.from("entries").select("id, jenis, berat, waktu_input").eq("kapal_id", kapal_id).order("waktu_input", { ascending: true });
    if (entriesError) {
      return { content: [{ type: "text", text: entriesError.message }], isError: true };
    }
    const perSpecies = {};
    let total = 0;
    for (const e of entries ?? []) {
      perSpecies[e.jenis] = (perSpecies[e.jenis] ?? 0) + Number(e.berat);
      total += Number(e.berat);
    }
    const payload = {
      ship,
      entries: entries ?? [],
      totals: { per_species: perSpecies, total_kg: total }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-fish-species.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_fish_species_default = defineTool3({
  name: "list_fish_species",
  title: "Daftar jenis ikan",
  description: "List the active fish/squid species catalog (nama ikan, nama latin, kategori, harga).",
  inputSchema: {
    search: z3.string().trim().min(1).optional().describe("Filter by name (case-insensitive)."),
    kategori: z3.string().trim().min(1).optional().describe("Filter by kategori.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, kategori }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("fish_species").select("id, nama_ikan, nama_latin, kategori, harga, is_active").eq("is_active", true).order("urutan", { ascending: true });
    if (search) query = query.ilike("nama_ikan", `%${search}%`);
    if (kategori) query = query.eq("kategori", kategori);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { species: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-catch-entry.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var add_catch_entry_default = defineTool4({
  name: "add_catch_entry",
  title: "Tambah data hasil bongkar",
  description: "Add a catch entry (jenis + berat in kg) to an existing ship unloading record owned by the signed-in user.",
  inputSchema: {
    kapal_id: z4.string().uuid().describe("Target ship record id."),
    jenis: z4.string().trim().min(1).describe("Species name, e.g. 'Peperek'."),
    berat: z4.number().positive().describe("Weight in kilograms.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ kapal_id, jenis, berat }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    if (!userId) {
      return { content: [{ type: "text", text: "Missing user identity in token" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("entries").insert({ kapal_id, jenis, berat, user_id: userId }).select("id, kapal_id, jenis, berat, waktu_input").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "umkoilkbffvqntebrrhx";
var mcp_default = defineMcp({
  name: "catat-laut",
  title: "Catat Laut",
  version: "0.1.0",
  instructions: "Tools for Catat Laut, the PPN Tegalsari ship unloading data system. Use `list_ships` to find ship unloading records, `get_ship_detail` for a ship's catch entries and totals, `list_fish_species` for the species catalog, and `add_catch_entry` to record a new catch weight. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_ships_default, get_ship_detail_default, list_fish_species_default, add_catch_entry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
